grammar org.lilypond.LilyPond

hidden(WS, SL_COMMENT, ML_COMMENT)

generate lilyPond "http://www.lilypond.org/LilyPond"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

LilyPond: expressions+=TopLevelExpression*;

terminal WS: WS_CHAR+;

terminal WS_CHAR: " " | "\t" | "\r" | "\n";

terminal SL_COMMENT: "%" !("\n" | "\r")* ("\r"? "\n")?;

terminal ML_COMMENT: "%{" -> "%}";

terminal TopLevelExpression: (!WS_CHAR)+;