<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lilypond"
    nsURI="http://www.elysium.org/LilyPond" nsPrefix="lilypond">
  <eClassifiers xsi:type="ecore:EClass" name="LilyPond">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//ToplevelExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToplevelExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//SchemeBlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommonExpression" eSuperTypes="#//ToplevelExpression #//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//ToplevelExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAssignment" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//CommonExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimultaneousBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//CommonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnparsedBlock" eSuperTypes="#//UnparsedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//UnparsedExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnparsedExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnparsedCommand" eSuperTypes="#//UnparsedExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" eType="#//Assignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//CommonExpression #//UnparsedExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//CommonExpression #//UnparsedExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialCommand" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Markup" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//MarkupBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkupLines" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//MarkupBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkupBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//UnparsedExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//UnparsedBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockCommand" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//SimpleBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDefinition" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//UnparsedBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeMusic" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pitch" eType="#//Pitch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="music" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pitch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="octaveCheck" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="octaveShift" eType="#//Octave"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reminderAccidental" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cautionaryAccidental" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Octave">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="up" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="down" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewContext" eSuperTypes="#//SpecialCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modification" eType="#//ContextModification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="music" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextModification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//UnparsedBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Other" eSuperTypes="#//SpecialCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scheme" eSuperTypes="#//CommonExpression #//UnparsedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SchemeExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quoted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quasiquoted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unquoted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SchemeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeBoolean" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeList" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//SchemeExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeBlock" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SchemeBlockElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeBlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeReference" eSuperTypes="#//SchemeBlockElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeCharacter" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeText" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeNumber" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemeMarkupCommand" eSuperTypes="#//SchemeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
