/*
 * generated by Xtext 2.10.0
 */
package org.elysium;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LilyPondStandaloneSetup extends LilyPondStandaloneSetupGenerated {

	public static void doSetup() {
		new LilyPondStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
}
